### ISSUE TITLE
Remove duplicate elements from sorted Array 

### ISSUE THREAD

**Issue by riyasingh775** [Shashwat-Sahu/CP-DSA#25]
Given an integer array, nums sorted in non-decreasing order, remove the duplicates in place such that each unique element appears only once. 

If there are k elements after removing the duplicates, then the first k elements of nums should hold the final result.

Return array containing all distinct elements after placing the final result in the first k slots of nums.

Example :

Input:
N = 3
Array = {1, 2, 2}
Output: 1 2
Explanation: After removing all the duplicates only two elements i.e., 1 and 2 will remain.

**Comment by riyasingh775** [comment]
@Shashwat-Sahu I have done PR with complexity O(n). Please review it!

**Comment by Shashwat-Sahu** [comment]
Ok @riyasingh775 saw that, done it !
